### ISSUE TITLE
A_client_publishing_Should_dispatch_to_all_subscribed_clients Test Racy

### ISSUE THREAD

**Issue by owainc** [danielwertheim/mynatsclient#14]
Sometimes fails as `Sync.Reset` is called twice before the main thread calls the first `Sync.WaitOne` so deadlocks.

**Comment by danielwertheim** [comment]
Thanks

**Comment by danielwertheim** [comment]
@owainc is this still an issue? Never happens to me since test framework has been switched and dot net core changes has been implemented.
