### ISSUE TITLE
Nats-streaming Support

### ISSUE THREAD

**Issue by tonymobster** [danielwertheim/mynatsclient#30]
Nice library. Any plans on adding nats-streaming support?

**Comment by ChristianWeyer** [comment]
Is there any realistic chance for this @danielwertheim ? ;-)

**Comment by danielwertheim** [comment]
Will look into it. But as I have no use for it myself and aren't paid to do it... I will at least look into it and see how much work it is so that I can come up with some sort of ETA.

**Comment by danielwertheim** [comment]
@tonymobster @ChristianWeyer First step is taken which brings support for Protobuf (v0.13.0) which is used in STAN. The idea is to have a `MyNatsClient.Stan` package or similar that defines the messages (protocol) and potentially a `StanClient`.

**Comment by danielwertheim** [comment]
For STAN support I would look into the official client for STAN (https://github.com/nats-io/stan.net) as MyNatsClient will await and see what happens with JetStream: https://nats.io/blog/tech-preview-oct-2019/
