### ISSUE TITLE
Error when parsing NatsServerInfo with IPv6 addresses

### ISSUE THREAD

**Issue by jasper-d** [danielwertheim/mynatsclient#37]
The NatsServerInfo.SplitToKeyValues method throws an exception if the JSON string contains IPv6 addresses. A failing test can be found here: https://github.com/jasper-d/mynatsclient/commit/62f84d3556e1ae4958c02fa7b4faf941a0a3e596

I would propose to revert #6 or use another battle tested JSON reader (such as Utf8JsonReader for .NET Core >= 3.0).

**Comment by danielwertheim** [comment]
Thanks for reporting. The idea was (and still is) to not have a dependency on a JSON lib in the core lib, until really needed (model gets to complex).

Will happily accept a PR with bug fix

**Comment by danielwertheim** [comment]
Fixed in #39
