### ISSUE TITLE
Client does not detect complete server failures

### ISSUE THREAD

**Issue by watfordgnf** [danielwertheim/mynatsclient#51]
Simulating a complete loss of the NATS server I found that the ClientDisconnected event is never raised and the auto-reconnect logic is never invoked.
```
PS C:\> docker start nats
nats
PS C:\> # run the test
PS C:\> docker stop nats
nats
```
Observing the log it appears the worker thread quits without any notice:
```
MyNatsClient.Events.ClientConnected
```
Reviewing the code I believe the following is the cause:
https://github.com/danielwertheim/mynatsclient/blob/0fc0815134cb16ee52901e52589458db28297916/src/MyNatsClient/NatsClient.cs#L229-L234

Because `ShouldDoWork` relies on the underlying connection's `IsConnected` and `CanRead` property, the exception received in the worker loop will be ignored and the worker will terminate as if requested by the client itself. The exception received is `ConnectionReset` in this case, and should indicate that the server failed and we should reconnect.

**Comment by danielwertheim** [comment]
@watfordgnf some more work has been done in this area and has now been released in `v0.19.1`
