### ISSUE TITLE
OnError is not fired on exception

### ISSUE THREAD

**Issue by sergeyshaykhullin** [danielwertheim/mynatsclient#57]
```cs
public class A
{
  public int B { get; set; }
}

var host = new Host("localhost", 4222);
var connection = new ConnectionInfo(host);
using var client = new NatsClient(connection);

await client.ConnectAsync();

using var subscription = await client.SubAsync(
  new SubscriptionInfo("subject", "queue"),
  stream => stream
    .Subscribe(
      onNext: op => throw new Exception("EXCEPTION"),
      onError: ex => Console.WriteLine(ex.Message),
      onCompleted: () => Console.WriteLine("COMPLETED")));

for (var i = 0; i < 10; i++)
{
  await client.PubAsJsonAsync("subject", new A {B = i});
}

Console.ReadKey();
```

1. Verbose = true prints nothing
2. `client.Events.OfType<ClientWorkerFailed>().Subscribe(ev
				=> Console.WriteLine($"Client consumer failed with Exception: '{ev.Exception}'."));` is not fired
3. AnonymousObserver is not handling exceptions

I found that SubAsync(_ => _.Subscribe(...)) using SafeObserver
![image](https://user-images.githubusercontent.com/46970457/93479735-5259f000-f905-11ea-9015-386c8b0be1ca.png)

**Comment by danielwertheim** [comment]
Not all parts are using Safe. The anonymous is not using the safe track: https://github.com/danielwertheim/mynatsclient/blob/master/src/MyNatsClient/Rx/NatsObservableExtensions.cs#L24

What's most likely happening is, that it's hitting this point: https://github.com/danielwertheim/mynatsclient/blob/master/src/MyNatsClient/NatsObservable.cs#L72

I do realize the docs weren't updated when this behavior switched. It was based upon the fact that it's not the producer that throws the exception: https://docs.microsoft.com/en-us/dotnet/api/system.iobserver-1.onerror?view=netcore-3.1

Wouldn't a `CatchObserver` be a more correct fit if you want to act upon it?

**Comment by danielwertheim** [comment]
Something like this: https://github.com/danielwertheim/mynatsclient/pull/60

**Comment by sergeyshaykhullin** [comment]
I think CatchObserver is more intuitive
