### ISSUE TITLE
Add useful client methods

### ISSUE THREAD

**Issue by sergeyshaykhullin** [danielwertheim/mynatsclient#58]
- [ ] RequestAsJsonAsync
- [ ] RespondAsJsonAsync
- [ ] PubManyAsync
- [ ] PubManyAsJsonAsync

**Comment by danielwertheim** [comment]
As there's `PubAsJson` I suppose it would make sense. Let me know if you are working on it.

**Comment by danielwertheim** [comment]
Not sure the async overloads of `PubMany` would bring so much as the existing `PubMany` takes a writer that allows for both sync and async writes. Hence it would "only" be the lock part if I'm not misstaken.

**Comment by sergeyshaykhullin** [comment]
Does PubMany using sync or async writer methods?

**Comment by danielwertheim** [comment]
That's up to the caller: https://github.com/danielwertheim/mynatsclient/blob/master/src/MyNatsClient/IPublisher.cs

The caller is provided a publisher in a callback.
