### ISSUE TITLE
NatsClient.Worker can execute only one message per time

### ISSUE THREAD

**Issue by sergeyshaykhullin** [danielwertheim/mynatsclient#59]
1. Since NatsClient.Worker is just one Task, this library can process only one message per time:
```cs
natsClient._consumer = (Task) Task.Factory.StartNew(
  new Action(natsClient.Worker),
  natsClient._cancellation.Token,
  TaskCreationOptions.LongRunning, TaskScheduler.Default)
```

2. So `test.1` can processed immedialty, but is waiting for `test.0` processing
```cs
await client.SubAsync("test.0", observable => observable.Subscribe(op =>
{
	Console.WriteLine("1 START");
	Thread.Sleep(1000);
	Console.WriteLine("1 END");
}));

await client.SubAsync("test.1", observable => observable.Subscribe(op =>
{
	Console.WriteLine("2 START");
	Console.WriteLine("2 END");
}));

for (int i = 0; i < 10; i++)
{
	await client.PubAsJsonAsync($"test.{i % 2}", new A {B = i});
}
```

3. `Task.Factory.StartNew` using `TaskScheduler.Default` by default without overrides. When NatsClient.Worker is single threaded it is not a problem, but if it will be of `1`/`2`, not being able to change the TaskScheduler would be a problem.
Example of dedicated thread pool on N reserved threads to consume https://github.com/quartznet/quartznet/blob/master/src/Quartz/Util/QueuedTaskScheduler.cs

**Comment by danielwertheim** [comment]
Feel free to show an example of how you would like to be able to inject a worker manager to control the behavior.

Why would you block the tread and not use async flow in the handler?

**Comment by sergeyshaykhullin** [comment]
Sleep is just synchronous "cpu intensive" workload.

You can't use Observable.Subscribe with async, because it will be async void. You read ops in a loop, so it is potentially infinite concurrency and thread starvations. For Console.Out.WriteLineAsync it will work, it is pretty fast and predictable, but if you are calling db it will be a big problem

**Comment by danielwertheim** [comment]
```csharp
        public static async Task Main(string[] args)
        {
            var cnInfo = new ConnectionInfo("localhost");

            _client = new NatsClient(cnInfo);

            await _client.ConnectAsync();

            _client.Sub("foo", stream => stream.Subscribe(async msg =>
            {
                Console.WriteLine("1");
                
                await Task.Delay(1000);
            
                Console.WriteLine($"1:{msg.GetPayloadAsString()}");
            }));

            _client.Sub("foo", stream => stream.Subscribe(async msg =>
            {
                Console.WriteLine("2");
                
                await Task.Delay(1500);

                Console.WriteLine($"2:{msg.GetPayloadAsString()}");
            }));

            await Task.Run(() =>
            {
                while (true)
                {
                    Console.WriteLine("Query? (y=yes;n=no)");
                    if (Console.ReadKey().KeyChar == 'n')
                        break;

                    Console.WriteLine();

                    _client.PubAsync("foo", DateTime.UtcNow.ToString("O"));
                }
            });

            _client.Disconnect();
        }
    }
```

**Comment by sergeyshaykhullin** [comment]
@danielwertheim I found that i mean https://github.com/dotnet/reactive/issues/459 this issue explains better

**Comment by danielwertheim** [comment]
Well, then what you want is to change out the Stream observable implementation (most likely this part: https://github.com/danielwertheim/mynatsclient/blob/master/src/MyNatsClient/NatsObservable.cs#L62) so that you can dispatch the `OP` in anyway you see fit.

MyNats doesn't rely on RX lib. Hence as of now, it's "just" function calls and you should be able to have any observers you see fit. If you make aliases and e.g an `AsyncObserver` and feel that it has a good place in here I'll gladly include it. You should also be able to extend the observer by using RX.Net, so if there's anything in there solving the issue, that should work, right?

The consumer scheduling has now been somewhat opened up so that you can inject a factory (via #61).

**Comment by danielwertheim** [comment]
Feel free to open a new request seen to the Observable. Or re-open this one if there's something I've missed.

**Comment by sergeyshaykhullin** [comment]
Yes, this that i need.
ConsumerFactory can be used for ThreadPoolConsumers and also in Scoped Consumer for ASP.Net Core package if it will be.
@danielwertheim  Maybe threadpool queue based consumer factory can be a part of core nats library?

**Comment by danielwertheim** [comment]
I do believe such an implementation of an IConsumerFactory would be a good contribution to the Core lib. Unless it has "weird" external dependencies, then it will have to reside in a new package.
