### ISSUE TITLE
Support to change connection name

### ISSUE THREAD

**Issue by hoangitk** [danielwertheim/mynatsclient#64]
Hi,

I would like to see specific name for each connection for tracking easier like can see which is subscriber/publisher:
![image](https://user-images.githubusercontent.com/342078/96101633-dfda3100-0eff-11eb-88a0-6c3c425a3f5a.png)

As I see in GenerateConnectionOpString, it is fixed "mynatsclient".

Thank you and regards!

**Comment by danielwertheim** [comment]
Just opened a PR that would solve this. Not sure if that is enough?

**Comment by hoangitk** [comment]
Wow, really appreciate 😍
