### ISSUE TITLE
Question: Best usage for asp.net api req/reply

### ISSUE THREAD

**Issue by smiziara** [danielwertheim/mynatsclient#68]
Dear,

What would be the best way to use with Asp.net web api? 
Our scenario is that a Http request must publish a request into Nats and await for the response, to return for the http caller. 
One client connection for the entire api would be a problem? Should we create a connection pooling? 
Thanks!

**Comment by danielwertheim** [comment]
There's no pooling built-in. With regards to request-response in the client, if you were to setup one client that serves many visitors, the idea is, that by default, there will be one subscription that handles responses and that each request gets its own ID: https://github.com/danielwertheim/mynatsclient/blob/master/src/MyNatsClient/NatsClient.cs#L536

When-ever a response is received it will mediate the response to the awaiting request via a `TaskCompletionSource` https://github.com/danielwertheim/mynatsclient/blob/master/src/MyNatsClient/NatsClient.cs#L530
