### ISSUE TITLE
Error with natsclient

### ISSUE THREAD

**Issue by thyn** [danielwertheim/mynatsclient#69]
I'm  occasionally  receiving errors like

"Error while parsing MSG. Expected char code '13' got '110'." There is always expected 13 character but receiving another

**Comment by danielwertheim** [comment]
Can you provide some sample code that reproduces this so that I can see how you use it?

**Comment by thyn** [comment]
Nat server  docker image is nats:2.1.9-alpine3.12

**Comment by igoree** [comment]
Unfortunately the bug is not fixed completely. The error became rare on small and medium messages but still occurs. You can reproduce it if you increase the message size in the test. Try 999999 - this value is close to default server limit and 100% doesn't work

**Comment by danielwertheim** [comment]
You are right. The mistake is on me. Mental breakdown as I was increasing the consumed counter with an extra 1.

Fix is on its way.

**Comment by danielwertheim** [comment]
New fix released in v0.18.1
