### ISSUE TITLE
mynatsclient throws lots of System.Net.Sockets.SocketException' and 'System.IO.IOException' in System.Net.Sockets.dll

### ISSUE THREAD

**Issue by Jaegermeiste** [danielwertheim/mynatsclient#83]
Using the latest 0.18.2 nuget in a .NET 5 project, and seeing LOTS of the below originating in mynatsclient when communication traffic is idle:

Exception thrown: 'System.Net.Sockets.SocketException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll

It appears that the client is attempting to read from the socket without checking if there is data available to read first, as with this line in NatsOpStreamReader.cs/ReadMsgOpBytes:  

```
while (true) {
  var read = source.Read(payload.Slice(consumed));    // Exception thrown here when no data available
  // Do stuff
}
```

Because the mynatsclient library uses the parent Stream class and not NetworkStream, the DataAvailable method isn't available to be checked, but converting the library to use the derived NetworkStream class would allow checks like this:

```
while(true) {
  if (source.DataAvailable) {
    var read = source.Read(payload.Slice(consumed));     // Theoretically we never read an empty stream, so no exception
    // Do stuff
  }
}
```

NetworkStream is available in .NET Core 3.1: https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream?view=netcore-3.1

This would clean up a lot of the exceptions being thrown.

**Comment by Jaegermeiste** [comment]
On digging further I see that the abstract class is used in order to support SSL sockets as well, and there is no great way to handle the various stream flavors without a spaghetti of code paths. Given that the .DataAvailable property is not universally available on streams and is a .NET limitation, I'm closing this issue.

**Comment by danielwertheim** [comment]
Thanks for reporting. Improvements made in `v0.19.1`

You will still be able to see a notification about this in the log:

```
warn: MyNatsClient.NatsClient[0]
      Consumer task got SocketException with error code TimedOut Frequency of Timeouts is controlled via ReceiveTimeout.
```

You can control the amount of time it will use for `ReceiveTimeout` in case you wan't it less frequent.

There will still be times when it logs exceptions (fail) in this area, e.g. if the server restarts as the socket then is shutdown. The reconnect process will kick in (if configured). E.g. of error log in this scenario:

```
warn: MyNatsClient.NatsClient[0]
      Consumer task got SocketException with error code TimedOut Frequency of Timeouts is controlled via ReceiveTimeout.
```
