### ISSUE TITLE
Client does not detect server failures

### ISSUE THREAD

**Issue by petedavis** [danielwertheim/mynatsclient#89]
This feels like a repeat of #51 

If I kill the nats server, the client will close without error and not reconnect.

In my case the if I stop the server, and then send a request, the caller of the caller will see an error, and the client will not reconnect.

The issue seems to be that there is no exeception during the `ConsumeWork` method, and the IsConnected becomes false. So the `ContinueWith` sees `t.IsFaulted == false` so it returns.

I can replicate this behaviour using the Request Response sample program.

Seeing same behaviour on Windows and Linux.

**Comment by danielwertheim** [comment]
Thanks for reporting. Fix released in `v0.19.1`
